spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8888
